edits
added -i for size info

diff --git a/cloud-dl b/cloud-dl
--- a/cloud-dl
+++ b/cloud-dl
@@ -115,6 +115,19 @@ list_shares(){
     [[ "$n" == "0" ]] && echo "[*] No shares found"
 }
 
+info(){
+    [ -z "$1" ] && echo "[!] Error. No share folder specified" && exit
+    dir=$(echo $1 | sed 's/ /%20/g')
+    res=$(curl $extra_opts $options -X PROPFIND $dav_url/$dir 2>/dev/null)
+    [ $? -gt 0 ] && echo '[!] Error listing files' && exit
+    [ -z $trail ] || trail=${trail}/
+    f="$(parse_xml "$res" "d:quota-used-bytes" | head -1)"
+    l="$(parse_xml "$res" "d:href" | sed -e "s|/$trail$path||g" -e 's/%20/ /g')"
+    s="$(parse_xml "$res" "d:getcontentlength" | sed -e "s|/$trail$path||g" -e 's/%20/ /g')"
+	echo "# files and sizes (folder size: ${f})"
+    paste <(echo -e "$l\n") <(echo -e "$f\n$s") | column -s $'\t' -t
+    }
+
 share(){
   [ -z "$1" ] && echo "[!] Error. No file specified" && exit
   shr_pwd=""
@@ -197,6 +210,9 @@ parse_args(){
             -L|--list-shares)   list_shares
             shift
             ;;
+            -i|--info)      info "$2"
+            shift
+            ;;
             -s|--share)     share "$2" "$3" "$4"; exit
             shift
             ;;
@@ -232,6 +248,7 @@ usage(){
     echo "   -s/--share <file|dir> [-p] [-q] Create a public share and shows the url. Optionally -p prompts for a password, -q returns only the share URL"
     echo "   -S/--share2 <file|dir> <password> <days to share> Create a public share with password and returns the url, password, and <sharing end date>"
     echo "   -L/--list-shares                List shares"
+    echo "   -i/--info [dir]                 Get info for a share [dir]"
     echo "   -U/--unshare <file|dir>         Delete a public share"
     echo "   --configure                     Change connection configuration"
     echo "   -h/--help                       Show this help"
